# Generated by Django 4.2.7 on 2023-11-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_places',
            name='image',
            field=models.TextField(max_length=400),
        ),
    ]
