# Generated by Django 4.2.7 on 2023-11-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_alter_food_places_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_places',
            name='image',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
